/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.Doctor.Doctor;
import Business.EcoSystem;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BookAppointment;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shreyascr
 */
public class DoctorAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorAdminJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount user;
    String hospname;
    
    public DoctorAdminJPanel(JPanel userProcessContainer,EcoSystem system,UserAccount user) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.user = user;
        viewTable();
        jPanel1.setVisible(false);
    }
public void viewTable(){
         //System.out.println(system.getWorkQueue().findWorkRequest(user));
        //WorkRequest work = system.getWorkQueue().findWorkRequest(user);
        DefaultTableModel dtm = (DefaultTableModel) doctorDetails.getModel();
        dtm.setRowCount(0);
//        
//         //System.out.println("Res len "+ system.getDoctorDirectory().getDoctorList());
//         for(int i = 0;i< system.getHospitalDirectory().getHospitalList().size();i++){
//              for(int j = 0;j< system.getHospitalDirectory().getHospitalList().get(i).getDoctorDirectory().getDoctorList().size();j++){
//              System.out.println(user.getEmployee().getName());
//              System.out.println(system.getHospitalDirectory().getHospitalList().get(0).getDoctorDirectory().getDoctorList().get(1).getName());
//             if(user.getEmployee().getName().equals(system.getHospitalDirectory().getHospitalList().get(i).getDoctorDirectory().getDoctorList().get(j).getName())){
//                 System.out.println("true true true");
//                 hospname = system.getHospitalDirectory().getHospitalList().get(i).getName();
//             }else{
//                 System.out.println("nothing");
//                         
//             }}
//         }
        
       if( system.getWorkQueue()!=null){
        for(WorkRequest wq :system.getWorkQueue().getWorkRequestList()) {
            // System.out.println("ssssss"+ wq.getSender().getEmployee().getName());
           
               // System.out.println("wq  "+wq );
                // System.out.println("work  "+work );
               // System.out.println("ssssss"+ wq.getSender().getEmployee().getName());
               if(wq instanceof BookAppointment){
            Object row[] = new Object[4];
            row[0] = wq;
             row[1] = wq.getMessage();
            row[2] = wq.getStatus();
            row[3] = wq.getRequestDate();
            dtm.addRow(row);
        }}}
    }
public void viewTable1(String name){
//        
        DefaultTableModel dtm = (DefaultTableModel) doctorDetails1.getModel();
        dtm.setRowCount(0);
//        
//         //System.out.println("Res len "+ system.getDoctorDirectory().getDoctorList());
        // int selectedRow = doctorDetails.getSelectedRow();
         int row1 = doctorDetails.getSelectedRow();
        int column = 0;
        String value = doctorDetails.getModel().getValueAt(row1, column).toString();
        for(WorkRequest wq : system.getWorkQueue().getWorkRequestList()) {
            if(wq instanceof BookAppointment){
                System.out.println("reciever "+value);
                if(wq.getSender().getEmployee().getName().equals(value)){
//                System.out.println("comm" + ((BookAppointment) wq).getComments());
           Object row[] = new Object[5];
            row[0] = wq.getSender().getEmployee().getName();
//            System.out.println("meds are" +((BookAppointment) wq).getMeds().getMedicines());
            
                for(int i=1;i<=(((BookAppointment) wq).getMeds().getMedicines()).size();i++){
                    for(String m:((BookAppointment) wq).getMeds().getMedicines()){
//                    System.out.println(((BookAppointment) wq).getMeds().getMedicines());
                    row[i] = m;
                    i++;
            }
            }
            row[4]=((BookAppointment) wq).getComments();
            dtm.addRow(row);
            }}}
           
        
         jPanel1.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        doctorDetails = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        doctorDetails1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctorDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient name", "Patient symtoms", "Patient Booking Status", "Booked Time"
            }
        ));
        jScrollPane1.setViewportView(doctorDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 680, 119));

        jButton1.setBackground(new java.awt.Color(24, 31, 46));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check prescription");
        jButton1.setPreferredSize(new java.awt.Dimension(156, 43));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        doctorDetails1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "medicine 1", "medicine 2", "medicine 3", "comments"
            }
        ));
        jScrollPane2.setViewportView(doctorDetails1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 600, -1));

        jButton2.setBackground(new java.awt.Color(24, 31, 46));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Create a prescription");
        jButton2.setPreferredSize(new java.awt.Dimension(156, 43));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Doctor Dashboard");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 180, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/shreyascr/Desktop/AED final/AED_final_project/icons/Humaaans - Standing.png")); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 60, 410, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = doctorDetails.getSelectedRow();
        int column = 0;
        String value = doctorDetails.getModel().getValueAt(row, column).toString();
        if(row < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        viewTable1(value);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = doctorDetails.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        BookAppointment pa = (BookAppointment)doctorDetails.getValueAt(selectedRow,0);
        PrescriptionJPanel prescriptionJPanel = new PrescriptionJPanel(userProcessContainer, system,pa);
        userProcessContainer.add("add Prescription", prescriptionJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable doctorDetails;
    private javax.swing.JTable doctorDetails1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
